// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVHrghu_dgVrYVnJUxVGykrNx_AJgeNgI',
    appId: '1:126514775288:web:621b1dbd869a6c23b2670d',
    messagingSenderId: '126514775288',
    projectId: 'appdesastresnaturales',
    authDomain: 'appdesastresnaturales.firebaseapp.com',
    storageBucket: 'appdesastresnaturales.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJSI9tZiY-KOIsHU2m9UdzA-kK62iommI',
    appId: '1:126514775288:android:664756c5f6abd3e4b2670d',
    messagingSenderId: '126514775288',
    projectId: 'appdesastresnaturales',
    storageBucket: 'appdesastresnaturales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ32amsSRfcZ4hwWW-9JXCe2Rvcq5mmVE',
    appId: '1:126514775288:ios:b02ee857e633d504b2670d',
    messagingSenderId: '126514775288',
    projectId: 'appdesastresnaturales',
    storageBucket: 'appdesastresnaturales.firebasestorage.app',
    iosBundleId: 'com.example.miAppDesastres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ32amsSRfcZ4hwWW-9JXCe2Rvcq5mmVE',
    appId: '1:126514775288:ios:b02ee857e633d504b2670d',
    messagingSenderId: '126514775288',
    projectId: 'appdesastresnaturales',
    storageBucket: 'appdesastresnaturales.firebasestorage.app',
    iosBundleId: 'com.example.miAppDesastres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVHrghu_dgVrYVnJUxVGykrNx_AJgeNgI',
    appId: '1:126514775288:web:14e4831029e33d48b2670d',
    messagingSenderId: '126514775288',
    projectId: 'appdesastresnaturales',
    authDomain: 'appdesastresnaturales.firebaseapp.com',
    storageBucket: 'appdesastresnaturales.firebasestorage.app',
  );
}
